namespace LearnEnglish.Data.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class testVideo : DbMigration
    {
        public override void Up()
        {

            Sql("SET IDENTITY_INSERT [dbo].[Videos] ON");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (70, N'Course Overview.mp4', N'Videos/Course Overview', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> Course Overview', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (71, N'Introduction.mp4', N'Videos/Introduction', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> An Introduction to C# and .NET', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (72, N'Setup.mp4', N'Videos/Setup', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> An Introduction to C# and .NET', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (73, N'.NET.mp4', N'Videos/.NET', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> An Introduction to C# and .NET', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (74, N'The Common Language Runtime.mp4', N'Videos/The Common Language Runtime', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> An Introduction to C# and .NET', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (75, N'The Framework.mp4', N'Videos/The Framework', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> An Introduction to C# and .NET', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (76, N'The C# Language.mp4', N'Videos/The C# Language', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> An Introduction to C# and .NET', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (77, N'Hello, World.mp4', N'Videos/Hello, World', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> An Introduction to C# and .NET', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (78, N'The Compiler.mp4', N'Videos/The Compiler', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> An Introduction to C# and .NET', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (79, N'Visual Studio.mp4', N'Videos/Visual Studio', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> An Introduction to C# and .NET', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (80, N'Debugging.mp4', N'Videos/Debugging', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> An Introduction to C# and .NET', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (81, N'Are You Sleepy?.mp4', N'Videos/Are You Sleepy?', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> An Introduction to C# and .NET', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (82, N'Summary.mp4', N'Videos/Summary', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> An Introduction to C# and .NET', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (83, N'Introduction.mp4', N'Videos/Introduction', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> Classes and Objects', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (84, N'The Grade Book.mp4', N'Videos/The Grade Book', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> Classes and Objects', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (85, N'Classes and Objects.mp4', N'Videos/Classes and Objects', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> Classes and Objects', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (86, N'Constructors.mp4', N'Videos/Constructors', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> Classes and Objects', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (87, N'Classes and Variables.mp4', N'Videos/Classes and Variables', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> Classes and Objects', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (88, N'Reference Types.mp4', N'Videos/Reference Types', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> Classes and Objects', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (89, N'Access Modifiers.mp4', N'Videos/Access Modifiers', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> Classes and Objects', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (90, N'Statics.mp4', N'Videos/Statics', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> Classes and Objects', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (91, N'Statistics.mp4', N'Videos/Statistics', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> Classes and Objects', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (92, N'Computation.mp4', N'Videos/Computation', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> Classes and Objects', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (93, N'Summary.mp4', N'Videos/Summary', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> Classes and Objects', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (94, N'Introduction.mp4', N'Videos/Introduction', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> Assemblies', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (95, N'Assemblies.mp4', N'Videos/Assemblies', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> Assemblies', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (96, N'Browsing Assemblies.mp4', N'Videos/Browsing Assemblies', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> Assemblies', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (97, N'Referencing Assemblies.mp4', N'Videos/Referencing Assemblies', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> Assemblies', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (98, N'Unit Testing.mp4', N'Videos/Unit Testing', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> Assemblies', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (99, N'Tests and Access Modifiers.mp4', N'Videos/Tests and Access Modifiers', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> Assemblies', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (100, N'Tests and Floats.mp4', N'Videos/Tests and Floats', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> Assemblies', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (101, N'Summary.mp4', N'Videos/Summary', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> Assemblies', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (102, N'Introduction.mp4', N'Videos/Introduction', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> Types', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (103, N'Reference Types.mp4', N'Videos/Reference Types', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> Types', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (104, N'Value Types.mp4', N'Videos/Value Types', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> Types', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (105, N'struct and enum.mp4', N'Videos/struct and enum', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> Types', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (106, N'Passing Parameters.mp4', N'Videos/Passing Parameters', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> Types', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (107, N'ref and out.mp4', N'Videos/ref and out', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> Types', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (108, N'Immutability.mp4', N'Videos/Immutability', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> Types', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (109, N'Arrays.mp4', N'Videos/Arrays', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> Types', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (110, N'Summary.mp4', N'Videos/Summary', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> Types', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (111, N'Introduction.mp4', N'Videos/Introduction', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> Methods, Fields, Events, and Properties', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (112, N'Methods.mp4', N'Videos/Methods', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> Methods, Fields, Events, and Properties', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (113, N'Fields and Properties.mp4', N'Videos/Fields and Properties', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> Methods, Fields, Events, and Properties', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (114, N'Events.mp4', N'Videos/Events', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> Methods, Fields, Events, and Properties', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (115, N'Delegates.mp4', N'Videos/Delegates', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> Methods, Fields, Events, and Properties', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (116, N'Events Revisited.mp4', N'Videos/Events Revisited', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> Methods, Fields, Events, and Properties', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (117, N'Summary.mp4', N'Videos/Summary', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> Methods, Fields, Events, and Properties', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (118, N'Introduction.mp4', N'Videos/Introduction', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> Control Flow', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (119, N'Branching.mp4', N'Videos/Branching', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> Control Flow', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (120, N'Switching.mp4', N'Videos/Switching', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> Control Flow', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (121, N'Iterating.mp4', N'Videos/Iterating', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> Control Flow', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (122, N'Jumping.mp4', N'Videos/Jumping', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> Control Flow', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (123, N'Throwing.mp4', N'Videos/Throwing', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> Control Flow', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (124, N'Handling.mp4', N'Videos/Handling', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> Control Flow', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (125, N'Chaining.mp4', N'Videos/Chaining', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> Control Flow', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (126, N'Finally.mp4', N'Videos/Finally', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> Control Flow', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (127, N'Summary.mp4', N'Videos/Summary', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> Control Flow', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (128, N'Introduction.mp4', N'Videos/Introduction', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> Object Oriented Programming', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (129, N'The Pillars.mp4', N'Videos/The Pillars', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> Object Oriented Programming', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (130, N'Inheritance.mp4', N'Videos/Inheritance', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> Object Oriented Programming', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (131, N'Polymorphism.mp4', N'Videos/Polymorphism', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> Object Oriented Programming', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (132, N'Abstract Classes.mp4', N'Videos/Abstract Classes', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> Object Oriented Programming', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (133, N'Interfaces.mp4', N'Videos/Interfaces', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> Object Oriented Programming', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (134, N'Common Interfaces.mp4', N'Videos/Common Interfaces', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> Object Oriented Programming', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (135, N'Where to Go Next.mp4', N'Videos/Where to Go Next', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> Object Oriented Programming', N'0:00:00')");
            Sql("INSERT INTO [dbo].[Videos] ([Id], [Title], [Url], [Language], [Level], [Name], [TotalTime]) VALUES (136, N'Summary.mp4', N'Videos/Summary', N'en', 0, N'C# Fundamentals with Visual Studio 2015 ---> Object Oriented Programming', N'0:00:00')");
            Sql("SET IDENTITY_INSERT [dbo].[Videos] OFF");
        }

        public override void Down()
        {
        }
    }
}
